/**:
  ros__parameters:
    # node
    sensor_pub_hz: 100

    # comm interface
    comm_type: 'serial' # serial, ethernet, can
    serial:
      port: '/dev/ttyUSB0'
      baud_rate: 115200

    # steering config (refers to average front wheel angle in radian)
    max_steering_left: 0.524  # (left +, righ -)
    max_steering_right: -0.524  # (left +, righ -)
    neutral_steering: 0.0  # should be between max and min

    # throttle config (unit is implementation-dependant, typically unit-less out of 1.0)
    max_throttle: 1.0
    min_throttle: 0.1
    zero_throttle: 0.0  # should be smaller than min

    # brake config (in psi)
    max_brake: 2000.0
    min_brake: 200.0
    zero_brake: 0.0  # should be smaller than min

    # watchdog timeouts (in millisecond)
    control_timeout_ms: 100  # timeout for control packets
    comm_timeout_ms: 100  # timeout for heartbeat packets
    sensor_timeout_ms: 100  # timeout between two sensor pollings

    # joystick testing
    enable_js_sub: true

    js_throttle_axis: 1
    js_brake_axis: 1
    js_steering_axis: 3

    js_throttle_offset: 0.0
    js_brake_offset: 0.0
    js_steering_offset: 0.0

    js_throttle_scale: 1.0
    js_brake_scale: -1.0
    js_steering_scale: 1.0

